import {useState} from 'react'
import {Button} from '@/components/ui/button'
import {StudioSelect} from '@/components/ui/select'
import type {StrategyFields} from './StrategyEditor'
export default function ChatPlacementPreview({value,company,href,goal}:{value:StrategyFields;company:string;href:string;goal:string}){
 const [device,setDevice]=useState('电脑');const [matched,setMatched]=useState(true);
 const trigger=value.chatTrigger||'咨询相关产品';const topic=value.chatKeywords||'相关产品';const turns=value.chatTurns||3;
 const show=value.enabled&&matched&&(value.device==='全部设备'||value.device===device);
 const message=trigger==='询问价格或报价'?`请提供${topic}的报价。`:trigger==='索取产品资料'?`可以提供${topic}的详细资料吗？`:trigger==='达到对话轮次'?'请介绍一下适用方案。':`我想了解${topic}的选型方案。`;
 return <section className="chat-placement-preview"><div className="placement-preview-heading"><div><h3>智能客服对话页</h3><p className="subtle">满足条件后，推荐卡片作为客服消息出现在对话中。</p></div><StudioSelect label="客服预览设备" value={device} options={['电脑','平板','手机']} onChange={setDevice}/></div><div className="chat-preview-controls"><span>触发条件：{trigger}{trigger==='达到对话轮次'?` · ${turns} 条访客消息`:''}</span><div><Button size="sm" variant={!matched?'secondary':'ghost'} onClick={()=>setMatched(false)}>未满足条件</Button><Button size="sm" variant={matched?'secondary':'ghost'} onClick={()=>setMatched(true)}>满足条件</Button></div></div><div className={`chat-preview-window device-${device}`}><header><span className="chat-avatar">服</span><div><strong>{company}</strong><small>智能客服 · 在线</small></div></header><div className="chat-preview-messages"><span className="chat-time">当前会话</span><div className="chat-bubble assistant">您好，请问需要了解哪些产品或服务？</div>{matched&&trigger==='达到对话轮次'&&turns>1&&<small className="chat-time">此前已有 {turns-1} 条访客消息</small>}<div className="chat-bubble visitor">{matched?message:'您好，我先了解一下。'}</div><div className="chat-bubble assistant">{show?'根据您的需求，推荐您查看以下内容。':'请描述您的需求，我将为您提供相关信息。'}</div>{show&&<div className="chat-recommendation"><small>为您推荐</small><strong>{value.caption}</strong><p>查看产品介绍与服务方案</p><a href={`${href}&placement=${encodeURIComponent(value.name)}`} target="_blank" rel="noreferrer">{goal} ↗</a></div>}</div><div className="chat-preview-input">请输入您的问题…<span>发送</span></div></div><p className="subtle">{!value.enabled?'当前推送未启用。':value.device!=='全部设备'&&value.device!==device?'当前设备不在推送范围内。':matched?'条件已满足，推荐消息出现在客服回复之后。':'条件未满足，不发送推荐消息。'}点击推荐卡片后打开完整落地页。</p></section>
}
