import ChatPlacementPreview from './ChatPlacementPreview'
import {useEffect,useState} from 'react'
import {Button} from '@/components/ui/button'
import {StudioSelect} from '@/components/ui/select'
import {NAV_PAGES,type StrategyFields} from './StrategyEditor'
export default function CombinedPreview({placements,company,href,goal,selectedName}:{selectedName:string;placements:StrategyFields[];company:string;href:string;goal:string}){
 const [device,setDevice]=useState('电脑');const [page,setPage]=useState('首页');const [closed,setClosed]=useState<string[]>([]);
 const selected=placements.find(p=>p.name===selectedName);
 useEffect(()=>{setPage(selectedName==='首屏 Banner'?'首页':selected?.scopes?.[0]||'产品中心');setDevice(selected?.device==='全部设备'?'电脑':selected?.device||'电脑');setClosed([])},[selectedName,selected?.scopes?.join(','),selected?.device]);
 const active=placements.filter(p=>p.name!=='智能客服推送'&&p.enabled&&!closed.includes(p.name)&&(p.device==='全部设备'||p.device===device)&& (p.name!=='侧边广告位'||device==='电脑')&&(p.name==='首屏 Banner'?page==='首页':(p.scopes||['产品中心']).includes(page)));
 const promo=(name:string)=>{const p=active.find(p=>p.name===name);return p?<div className={`combined-promo ${selectedName===name?'focused-placement':''} promo-${name==='首屏 Banner'?'banner':name==='页中横幅'?'inline':name==='侧边广告位'?'side':name==='底部弹出'?'bottom':'chat'}`}><small>{p.name}</small><strong>{p.caption}</strong><a href={`${href}&placement=${encodeURIComponent(p.name)}`} target="_blank" rel="noreferrer">{goal} ↗</a>{['底部弹出','智能客服推送'].includes(name)&&<button aria-label={`关闭${name}`} onClick={()=>setClosed(old=>[...old,name])}>×</button>}</div>:null};
 if(selectedName==='智能客服推送'&&selected)return <ChatPlacementPreview value={selected} company={company} href={href} goal={goal}/>
 return <section className="combined-preview"><div className="placement-preview-heading"><div><h3>在网站中的展示位置</h3><p className="subtle">高亮当前选择的位置；访客点击推广入口后打开完整落地页。</p></div><StudioSelect label="推广预览设备" value={device} options={['电脑','平板','手机']} onChange={v=>{setDevice(v);setClosed([])}}/></div><div className="preview-nav-tabs">{NAV_PAGES.map(n=><Button key={n} size="sm" variant={page===n?'secondary':'ghost'} onClick={()=>{setPage(n);setClosed([])}}>{n}</Button>)}</div>{!selected?.enabled&&<p className="placement-empty-hint">请在左侧勾选「{selectedName}」，查看其在网站中的位置。</p>}{selected?.enabled&&!active.some(p=>p.name===selectedName)&&<p className="placement-empty-hint">当前导航页或设备不展示「{selectedName}」。可切换预览范围或调整设置。</p>}<div className={`combined-site device-${device}`}><nav><strong>{company}</strong><small>{page}</small></nav>{promo('首屏 Banner')}<div className="combined-hero"><small>PROFESSIONAL SOLUTIONS</small><h3>为专业工程，提供可靠支持</h3><p>产品信息与应用方案</p></div><div className="combined-body"><main><h4>{page} · 精选内容</h4><p/><p/>{promo('页中横幅')}<h4>应用与服务</h4><p/><p/></main>{device==='电脑'&&<aside>{promo('侧边广告位')}</aside>}</div>{promo('底部弹出')}</div><div className="resource-footer"><p className="subtle">网站示意预览 · {active.length} 个入口 · 假设已满足触发条件</p>{closed.length>0&&<Button size="sm" variant="ghost" onClick={()=>setClosed([])}>恢复已关闭入口</Button>}</div></section>
}
