import { useState } from 'react'
import { Folder, FileText, Upload, X, ExternalLink, ImageIcon, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { mockProductsData } from './blocks'
import type { Draft } from './MarketingStudio'
export const KNOWLEDGE_DIRS=['企业与品牌','产品资料','行业解决方案','客户案例','活动与展会','服务与常见问题']
export interface ResourceAsset {id:string;name:string;size:number;type:'image'|'document';url?:string}
export default function ResourcePanel({mode,draft,onChange,onClose,onUpload,uploadMode=false,selectedElement=''}:{mode:string;draft:Draft;onChange:(patch:Partial<Draft>)=>void;onClose:()=>void;onUpload?:()=>void;uploadMode?:boolean;selectedElement?:string}) {
 const [dirs,setDirs]=useState(draft.knowledgeDirs?.length?draft.knowledgeDirs:[...KNOWLEDGE_DIRS]);const [assets,setAssets]=useState<ResourceAsset[]>(draft.assets||[]);const [error,setError]=useState('');const [reading,setReading]=useState(false);const [selected,setSelected]=useState(draft.productIds);const [list,setList]=useState(false);const [query,setQuery]=useState('');const [category,setCategory]=useState('全部分类');const [chosenImage,setChosenImage]=useState('');const [note,setNote]=useState('');
 const upload=async(files:FileList|null)=>{if(!files)return;setReading(true);const next:ResourceAsset[]=[];const errors:string[]=[];for(const file of Array.from(files)){const isImage=mode==='image';if(isImage&&(file.size>10*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))){errors.push(`${file.name}：仅支持 10 MB 以内的 PNG、JPEG、WebP`);continue}if(!isImage&&!/\.(pdf|docx?|txt|md|xlsx?|pptx?)$/i.test(file.name)){errors.push(`${file.name}：不支持的文档格式`);continue}try{let url:string|undefined;if(isImage){const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const ratio=Math.min(1,1440/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);url=canvas.toDataURL('image/webp',.78);bitmap.close()}next.push({id:crypto.randomUUID(),name:file.name,size:file.size,type:isImage?'image':'document',url})}catch{errors.push(`${file.name}：文件读取失败`)}}setAssets(old=>[...old,...next]);if(next.find(x=>x.url))setChosenImage(next.find(x=>x.url)!.id);setError(errors.join('；'));setReading(false)}
 if(mode==='knowledge'&&!uploadMode)return <div className="resource-panel"><div className="resource-summary"><span><strong>知识检索范围</strong><small>按目录启用，生成时检索目录内的知识资料</small></span><Button variant="ghost" onClick={()=>setDirs(dirs.length===KNOWLEDGE_DIRS.length?[]:[...KNOWLEDGE_DIRS])}>{dirs.length===KNOWLEDGE_DIRS.length?'取消全选':'全部启用'}</Button></div><div className="directory-list">{KNOWLEDGE_DIRS.map((name,index)=><div className="directory-row" key={name}><span className="resource-icon"><Folder size={19}/></span><div><strong>{name}</strong><small>知识库 / {name}</small></div><button className="resource-switch" role="switch" aria-label={`检索${name}`} aria-checked={dirs.includes(name)} onClick={()=>setDirs(old=>old.includes(name)?old.filter(x=>x!==name):[...old,name])}><span/></button></div>)}</div><p className="subtle">{dirs.length?`已启用 ${dirs.length} 个目录`:'未指定目录，生成时自动检索全部目录。'}</p><div className="resource-footer"><Button variant="outline" onClick={onUpload}><Upload size={15}/>上传补充资料</Button><Button onClick={()=>{onChange({knowledgeDirs:dirs});onClose()}}>保存范围</Button></div></div>
 if(mode==='products')return <div className="resource-panel">{!list?<><div className="resource-summary"><span><strong>关联平台产品</strong><small>从产品列表选择，使用已有产品信息生成页面</small></span><Button variant="outline" onClick={()=>setList(true)}><ExternalLink size={15}/>打开产品列表</Button></div><div className="selected-product-names">{selected.length?mockProductsData.filter(p=>selected.includes(p.id)).map(p=><span key={p.id}>{p.name}<button aria-label={`移除${p.name}`} onClick={()=>setSelected(old=>old.filter(x=>x!==p.id))}><X size={13}/></button></span>):<p className="subtle">尚未关联产品</p>}</div><div className="resource-footer"><span>已选择 {selected.length} 个产品</span><Button onClick={()=>{onChange({productIds:selected});onClose()}}>完成</Button></div></>:<><div className="resource-summary"><strong>产品列表</strong><Button variant="ghost" onClick={()=>setList(false)}>返回关联设置</Button></div><div className="product-list-filters"><select aria-label="所属分类" value={category} onChange={e=>setCategory(e.target.value)}>{['全部分类',...new Set(mockProductsData.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select><Input aria-label="搜索产品名称" placeholder="请输入产品名称" value={query} onChange={e=>setQuery(e.target.value)}/><Search size={17}/></div><Table><TableHeader><TableRow><TableHead>选择</TableHead><TableHead>缩略图</TableHead><TableHead>产品名称</TableHead><TableHead>分类</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody>{mockProductsData.filter(p=>p.name.includes(query)&&(category==='全部分类'||p.category===category)).map(p=><TableRow key={p.id}><TableCell><input type="checkbox" aria-label={`选择${p.name}`} checked={selected.includes(p.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,p.id]:old.filter(x=>x!==p.id))}/></TableCell><TableCell><ImageIcon size={24}/></TableCell><TableCell>{p.name}</TableCell><TableCell>{p.category}</TableCell><TableCell>已发布</TableCell></TableRow>)}</TableBody></Table><p className="subtle">平台产品列表选择流程预览，当前使用示例产品。</p><div className="resource-footer"><span>已选择 {selected.length} 个产品</span><Button onClick={()=>{onChange({productIds:selected});setList(false)}}>确认选择</Button></div></>}</div>
 const imageMode=mode==='image';const visible=assets.filter(a=>a.type===(imageMode?'image':'document'));
 return <div className="resource-panel"><label className="resource-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!reading)void upload(e.dataTransfer.files)}}><Upload size={26}/><strong>{reading?'正在读取文件…':imageMode?'选择或拖入多张图片':'选择或拖入多个文档'}</strong><span>{imageMode?'PNG、JPEG、WebP · 每张不超过 10 MB':'PDF、Word、TXT、Markdown、Excel、PowerPoint'}</span><Input disabled={reading} aria-label={imageMode?'批量上传图片':'批量上传文档'} multiple type="file" accept={imageMode?'image/png,image/jpeg,image/webp':'.pdf,.doc,.docx,.txt,.md,.xls,.xlsx,.ppt,.pptx'} onChange={e=>{void upload(e.target.files);e.target.value=''}}/></label>{error&&<p className="error-text" role="alert">{error}</p>}<div className={imageMode?'resource-images':'resource-files'}>{visible.map(a=><div key={a.id} className={chosenImage===a.id?'chosen':''}>{imageMode?<button onClick={()=>setChosenImage(a.id)} aria-label={`使用${a.name}`}><img src={a.url} alt={a.name}/></button>:<FileText size={20}/>}<span title={a.name}>{a.name}<small>{(a.size/1024/1024).toFixed(2)} MB</small></span><Button size="icon" variant="ghost" aria-label={`移除${a.name}`} onClick={()=>{setAssets(old=>old.filter(x=>x.id!==a.id));if(chosenImage===a.id)setChosenImage('')}}><X size={14}/></Button></div>)}</div>{!imageMode&&<textarea className="studio-textarea" placeholder="补充业务说明（选填）" aria-label="补充业务说明" value={note} onChange={e=>setNote(e.target.value)}/>}<p className="subtle">{imageMode?'点击图片选择用于当前选区的素材，其余图片保留在素材列表。图片将压缩为预览副本。':'原型记录文件清单，文档解析与知识匹配使用模拟结果。'}</p><div className="resource-footer"><span>{visible.length} 个文件</span><Button disabled={reading||(!visible.length&&!note.trim())} onClick={()=>{const chosen=assets.find(a=>a.id===chosenImage)||visible[0];const patch:Partial<Draft>={assets};if(imageMode&&chosen){if(selectedElement.includes(':image')&&selectedElement!=='hero:image')patch.elementImages={...draft.elementImages,[selectedElement]:chosen.url!};else{patch.image=chosen.url!;patch.imageReady=true}}else{patch.knowledgeReady=true;patch.knowledgeName=visible.map(a=>a.name).join('、')||(note?'补充业务说明':'');if(note)patch.sections=draft.sections.map(s=>s.kind==='text'?{...s,body:note}:s)}patch.messages=[...draft.messages,{role:'检测助手',text:`已接收${visible.length}个${imageMode?'图片':'文档'}，资料校验完成（模拟）。`},{role:'生成助手',text:'已更新相关内容，可继续选择页面元素调整。'}];onChange(patch);onClose()}}>{draft.stage==='edit'?'提交补充资料':'保存资料'}</Button></div></div>
}
