import {useState,useRef} from 'react'
import type React from 'react'
import type { CSSProperties } from 'react'
import { ArrowRight, ArrowUpRight, Check, Layers3, ImageIcon, Play, Plus, GripVertical } from 'lucide-react'
import { inferKind, mockProductsData } from './blocks'
import type { Template, Section } from './MarketingStudio'
export function ProductIllustration({id='product'}:{id?:string}) {
 return <svg className="product-illustration" viewBox="0 0 520 450" role="img" aria-label="工业流体控制设备示意图"><defs><linearGradient id={`${id}-steel`} x1="0" x2="1"><stop stopColor="#94a6bb"/><stop offset=".2" stopColor="#f2f5f8"/><stop offset=".5" stopColor="#c5d0df"/><stop offset=".7" stopColor="#8da0b7"/><stop offset="1" stopColor="#dbe3ed"/></linearGradient><linearGradient id={`${id}-body`} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#71859c"/><stop offset=".4" stopColor="#dae3ed"/><stop offset="1" stopColor="#7588a0"/></linearGradient><filter id={`${id}-shadow`}><feGaussianBlur stdDeviation="15"/></filter></defs><ellipse cx="270" cy="380" rx="153" ry="23" fill="#192e54" opacity=".14" filter={`url(#${id}-shadow)`}/><g transform="translate(30 3)"><path d="M159 255 L159 216 Q159 189 219 185 L292 185 Q345 196 345 224 L345 290 Q332 320 273 320 L209 320 Q160 308 159 280Z" fill={`url(#${id}-body)`}/><ellipse cx="248" cy="211" rx="89" ry="32" fill="#dbe3ec"/><path d="M216 171 L216 237 Q248 253 280 237 L280 171Z" fill={`url(#${id}-steel)`}/><ellipse cx="248" cy="171" rx="32" ry="13" fill="#f1f4f8"/><path d="M229 115 L229 181 Q248 191 267 181 L267 115" fill={`url(#${id}-steel)`}/><path d="M202 292 L292 290 L300 326 L210 341 L190 327Z" fill="#a9b8c9"/><path d="M201 327 L290 315 L300 329 L211 350 L190 338Z" fill="#6e839a"/><path d="M96 235 L178 235 L178 285 L96 294Z" fill={`url(#${id}-steel)`}/><ellipse cx="103" cy="264" rx="32" ry="64" fill="#96a7bc"/><ellipse cx="93" cy="263" rx="29" ry="62" fill={`url(#${id}-steel)`}/><ellipse cx="92" cy="264" rx="18" ry="36" fill="#506680"/><ellipse cx="95" cy="264" rx="10" ry="29" fill="#273f5d"/><path d="M327 236 L385 210 L386 280 L330 300Z" fill={`url(#${id}-steel)`}/><ellipse cx="386" cy="242" rx="33" ry="63" fill="#8a9db4"/><ellipse cx="394" cy="242" rx="32" ry="63" fill={`url(#${id}-steel)`}/><ellipse cx="396" cy="241" rx="19" ry="36" fill="#526b88"/>{[205,240,278,312].map((y,i)=><g key={y}><ellipse cx={i===0||i===3?93:75} cy={y} rx="4" ry="5" fill="#627991"/><ellipse cx={i===0||i===3?394:415} cy={y-22} rx="4" ry="5" fill="#627991"/></g>)}<g transform="translate(248 108)"><ellipse rx="79" ry="28" fill="none" stroke="var(--page-accent)" strokeWidth="13"/><path d="M-70 -8 L68 8 M-53 20 L50 -20" stroke="var(--page-accent)" strokeWidth="8"/><ellipse rx="15" ry="7" fill="#2b4563"/><path d="M-15 0 V15 Q0 24 15 15 V0" fill="#344e69"/><ellipse rx="15" ry="7" fill="#dce4ed"/></g><path d="M173 253 Q249 278 331 246" fill="none" stroke="#fff" strokeOpacity=".35" strokeWidth="2"/><rect x="207" y="265" width="51" height="22" rx="2" transform="rotate(8 207 265)" fill="#49637e"/><path d="M215 274 l29 4 M215 280 l20 3" stroke="#d4e0ec" strokeWidth="2"/></g></svg>
}
export function TemplateCover({template}:{template:Template}) {
 return <div className={`template-cover cover-${template.layout} thumb-${template.id}`} style={{'--page-accent':template.color} as CSSProperties}><div className="mini-nav"><b><Layers3 size={9}/>STUDIO</b><span/><span/><span/></div><div className="mini-hero"><div className="mini-copy"><small>{template.tag}</small><h3>{template.headline}</h3><div className="mini-lines"><i/><i/></div><b className="mini-cta">{template.action}<ArrowUpRight size={8}/></b></div><div className="mini-art">{template.layout==='form-side'?<div className="mini-form"><b>开始专业沟通</b><i/><i/><i/><span/></div>:template.layout==='editorial'?<div className="architectural"><i/><i/><i/><i/></div>:template.id==='guide'?<div className="book-cover">THE<br/>SELECTION<br/>GUIDE</div>:<ProductIllustration id={`thumb-${template.id}`}/>}</div></div><div className="mini-bottom">{template.sections.slice(0,3).map(x=><span key={x}>{x}</span>)}</div></div>
}
interface CanvasDraft {demoVideo?:boolean;elementTexts?:Record<string,string>;elementImages?:Record<string,string>;textStyles?:Record<string,CSSProperties>;videoUrl?:string;heroTextColor?:string;company:string;title:string;subtitle:string;goal:string;color:string;layout:string;image:string;sections:Section[];secondary:string;imageReady?:boolean;knowledgeReady?:boolean;knowledgeName?:string;productIds?:string[];heroVisible?:boolean;footerVisible?:boolean;fontStyle?:string;logo?:string;optionalFields?:Record<string,string>;formFields?:string[]}
export function LandingCanvas({draft,template,editable=false,selected,onSelect,onAction,onDropBlock,formFields,selectedElement,onElementSelect}:{draft:CanvasDraft;template:Template;selectedElement?:string;onElementSelect?:(key:string,text?:string)=>void;editable?:boolean;selected?:string;onSelect?:(id:string)=>void;onAction?:(action?:string)=>void;onDropBlock?:(value:string,before?:string)=>void;formFields?:string[]}) {
 const articleRef=useRef<HTMLElement>(null)
 const act=(goal?:string)=>{const form=articleRef.current?.querySelector('form');if(form){form.scrollIntoView({behavior:'smooth',block:'center'});form.querySelector('input')?.focus()}else onAction?.(goal)}
 const [submittedForms,setSubmittedForms]=useState<string[]>([])
 const textProps=(key:string)=>({style:draft.textStyles?.[key],className:editable?`editable-text ${selectedElement===key?'text-selected':''}`:undefined,onClick:(e:React.MouseEvent)=>{if(editable){e.stopPropagation();onElementSelect?.(key,e.currentTarget.textContent||'')}}})
 const textValue=(key:string,fallback:string)=>draft.elementTexts?.[key]??fallback
 const choose=(id:string)=>{if(editable)onSelect?.(id)}
 const fields=formFields||draft.formFields||['姓名','邮箱','公司']
 const selectedProducts=mockProductsData.filter(p=>draft.productIds?.includes(p.id))
 const dropZone=(before?:string)=><div className="canvas-dropzone" aria-label="组件插入位置" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('drop-active')}} onDragLeave={e=>e.currentTarget.classList.remove('drop-active')} onDrop={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.classList.remove('drop-active');onDropBlock?.(e.dataTransfer.getData('text/plain'),before)}}><Plus size={13}/>拖入组件</div>
 const content=(s:Section)=>{
  const kind=s.kind||inferKind(s.title)
  const placeholder=(label:string)=><div className="content-placeholder"><ImageIcon size={22}/><span>{label}</span></div>
  if(kind==='features')return <div className="block-grid" style={{'--block-columns':s.columns||3} as CSSProperties}>{['场景适配','专业协作','持续支持'].map((name,i)=><div className="feature-tile" key={name}><span>0{i+1}</span><h3 {...textProps(`${s.id}:item-${i}`)}>{textValue(`${s.id}:item-${i}`,name)}</h3><p {...textProps(`${s.id}:body`)}>{draft.knowledgeReady?s.body:'[待补充：能力与服务依据]'}</p></div>)}</div>
  if(kind==='products')return <div className="block-grid" style={{'--block-columns':s.columns||3} as CSSProperties}>{selectedProducts.length?selectedProducts.map(p=><div className="product-tile" key={p.id}><div onClick={e=>{if(editable){e.stopPropagation();onElementSelect?.(`${s.id}:image-${p.id}`)}}} className={selectedElement===`${s.id}:image-${p.id}`?'text-selected':''}>{draft.elementImages?.[`${s.id}:image-${p.id}`]?<img src={draft.elementImages[`${s.id}:image-${p.id}`]} alt={p.name}/>:<ProductIllustration id={`${s.id}-${p.id}`}/>}</div><h3 {...textProps(`${s.id}:product-${p.id}`)}>{textValue(`${s.id}:product-${p.id}`,p.name)}</h3><p>{draft.optionalFields?.['产品规格/型号']||'[待补充：产品规格]'}</p><button onClick={e=>{e.stopPropagation();act(draft.goal)}}>了解产品 <ArrowUpRight size={12}/></button></div>):placeholder('待选择关联产品')}</div>
  if(kind==='comparison')return <table className="comparison-block"><thead><tr><th>对比维度</th><th>方案 A</th><th>方案 B</th></tr></thead><tbody>{['规格与型号','适用工况','交付与服务'].map(name=><tr key={name}><td>{name}</td><td>{name==='规格与型号'?draft.optionalFields?.['产品规格/型号']||'待补充':'待补充'}</td><td>待补充</td></tr>)}</tbody></table>
  if(kind==='testimonials')return <blockquote className="testimonial-block"><span>“</span><p {...textProps(`${s.id}:body`)}>{draft.knowledgeReady?s.body:'[待补充：经确认的客户案例与来源]'}</p><small {...textProps(`${s.id}:attribution`)}>{textValue(`${s.id}:attribution`,'客户名称与授权信息待补充')}</small></blockquote>
  if(kind==='gallery')return <div className="block-grid gallery-block" style={{'--block-columns':s.columns||3} as CSSProperties}>{[1,2,3].map(i=><div key={i} className={selectedElement===`${s.id}:image${i}`?'text-selected':''} onClick={e=>{if(editable){e.stopPropagation();onElementSelect?.(`${s.id}:image${i}`)}}}>{draft.elementImages?.[`${s.id}:image${i}`]||draft.image?<img src={draft.elementImages?.[`${s.id}:image${i}`]||draft.image} alt={`场景示意 ${i}`}/>:placeholder(`场景图片 ${i} · 待补充`)}</div>)}</div>
  if(kind==='stats')return <div className="block-grid stats-block" style={{'--block-columns':s.columns||3} as CSSProperties}>{['工厂面积','员工及研发人数','年产能'].map(name=><div key={name}><strong>{draft.optionalFields?.[name]||'—'}</strong><span>{name}</span>{!draft.optionalFields?.[name]&&<small>待补充依据</small>}</div>)}</div>
  if(kind==='timeline')return <div className="timeline-block">{['需求沟通','专业交流','方案确认'].map((name,i)=><div key={name}><b>0{i+1}</b><div><h3 {...textProps(`${s.id}:item-${i}`)}>{textValue(`${s.id}:item-${i}`,name)}</h3><p>{draft.optionalFields?.['展会时间']||s.body}</p></div></div>)}</div>
  if(kind==='faq')return <div className="faq-block">{['如何选择适用的产品？','咨询前需要准备哪些信息？','如何联系专业团队？'].map(q=><details key={q} onClick={e=>e.stopPropagation()}><summary>{q}</summary><p {...textProps(`${s.id}:body`)}>{draft.knowledgeReady?s.body:'[待补充：知识库中的问题解答]'}</p></details>)}</div>
  if(kind==='form')return <form className="inline-form-preview" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();setSubmittedForms(rows=>[...rows,s.id])}}>{submittedForms.includes(s.id)?<p role="status">提交成功（演示）。信息未发送到业务系统。</p>:<><div className="form-field-preview">{fields.map(field=><label key={field}>{field}<input required type={field==='邮箱'?'email':field==='预约日期'?'date':'text'} placeholder={`请输入${field}`} aria-label={field}/></label>)}</div><button type="submit" className="landing-cta">{draft.goal}<ArrowUpRight size={14}/></button><small>演示表单，不发送真实数据</small></>}</form>
  if(kind==='cta')return <div className="cta-block"><p>{draft.optionalFields?.['促销优惠内容']||s.body}</p><button className="landing-cta" onClick={e=>{e.stopPropagation();act(draft.goal)}}>{draft.goal}<ArrowRight size={14}/></button></div>
  if(kind==='video'&&draft.videoUrl)return <video className="block-video" controls src={draft.videoUrl} onClick={e=>e.stopPropagation()}/>
  if(kind==='video'&&draft.demoVideo)return <div className="video-placeholder"><Play size={36}/><p>演示视频素材</p><small>素材占位已确认 · 正式发布时替换实际视频</small></div>
  if(kind==='video')return <div className="video-placeholder"><Play size={36}/><p>视频素材待补充</p><small>首版保留播放区域</small></div>
  return <div className="text-block"><p {...textProps(`${s.id}:body`)}>{draft.knowledgeReady?s.body:'[待补充：知识资料依据]'}</p>{draft.knowledgeReady&&<small>内容依据：{draft.knowledgeName||'企业知识库（示例）'}</small>}</div>
 }
 return <article ref={articleRef} className={`landing-page landing-${draft.layout} font-${draft.fontStyle==='经典衬线'?'serif':draft.fontStyle==='技术等宽'?'mono':'sans'}`} style={{'--page-accent':draft.color||'#314ed8'} as CSSProperties}>
 <div className="landing-nav"><a href="#landing-hero" className="landing-brand">{draft.logo?<img className="brand-logo" src={draft.logo} alt="品牌 Logo"/>:<Layers3 size={20}/>}<span>{draft.company||'企业名称'}</span></a><div><a href="#landing-content">{template.type==='展会页面'?'展会信息':'产品与服务'}</a><a href="#landing-contact">联系我们<ArrowUpRight size={12}/></a></div></div>
 {draft.heroVisible!==false&&<section id="landing-hero" className={`landing-hero selectable ${editable?'can-select':''} ${editable&&selected==='hero'?'is-selected':''}`} onClick={()=>choose('hero')} tabIndex={editable?0:undefined} onKeyDown={e=>{if(editable&&e.target===e.currentTarget&&e.key==='Enter')choose('hero')}} aria-label={editable?'选择首屏区域':undefined}>
 {editable&&<><span className="region-label">首屏 · 点击选择</span></>}
 <div className="landing-copy"><p className="landing-eyebrow">{template.type==='展会页面'?'CONNECT. EXPLORE. CREATE.':'ENGINEERED FOR WHAT’S NEXT'}</p><h1 {...textProps('hero:title')}>{draft.title||template.headline}</h1><p {...textProps('hero:body')} className={`landing-description ${editable?'editable-text':''} ${selectedElement==='hero:body'?'text-selected':''}`}>{draft.subtitle}</p><div className="landing-actions"><button className="landing-cta" onClick={e=>{e.stopPropagation();act(draft.goal)}}>{draft.goal}<ArrowUpRight size={15}/></button>{draft.secondary!=='不设置'&&draft.secondary!==draft.goal&&<button className="landing-secondary" onClick={e=>{e.stopPropagation();act(draft.secondary)}}>{draft.secondary}</button>}</div><div className="landing-proof"><span><Check size={12}/>专业需求沟通</span><span><Check size={12}/>场景适配支持</span></div></div>
 <div className={`landing-visual ${selectedElement==='hero:image'?'text-selected':''}`} onClick={e=>{if(editable&&draft.layout!=='form-side'){e.stopPropagation();onElementSelect?.('hero:image')}}}>{draft.layout==='form-side'?<div className="hero-form-card"><h3>开启专业沟通</h3>{content({id:'hero-form',kind:'form',title:'联系表单',body:''})}</div>:draft.image?<img src={draft.image} alt="已选页面主图"/>:draft.imageReady===false?<div className="hero-placeholder"><ImageIcon size={36}/><strong>主图待补充</strong><span>可通过对话上传素材</span></div>:draft.layout==='editorial'?<div className="architectural full"><i/><i/><i/><i/></div>:<ProductIllustration id="hero"/>}<span className="visual-caption">{draft.image?'企业素材':draft.imageReady===false?'ASSET PLACEHOLDER':'CONCEPT VISUAL / 示意素材'}</span></div></section>}
 <div id="landing-content" className="composed-sections">{draft.sections.filter(s=>!s.hidden).map(s=><div key={s.id}>{editable&&dropZone(s.id)}<section id={`section-${s.id}`} draggable={editable} onDragStart={e=>{e.dataTransfer.setData('text/plain',`move:${s.id}`)}} className={`composed-block block-${s.kind||inferKind(s.title)} selectable ${editable?'can-select':''} ${editable&&selected===s.id?'is-selected':''}`} style={{color:s.color}} onClick={()=>choose(s.id)} tabIndex={editable?0:undefined} onKeyDown={e=>{if(e.target===e.currentTarget&&e.key==='Enter')choose(s.id)}} aria-label={editable?`选择${s.title}区域`:undefined}>{editable&&<><span className="region-label"><GripVertical size={12}/>{s.title}</span></>}<div className="block-heading"><h2 {...textProps(`${s.id}:title`)}>{s.title}</h2><p {...textProps(`${s.id}:body`)}>{s.body}</p></div>{content(s)}</section></div>)}{editable&&dropZone()}</div>
 {draft.footerVisible!==false&&<>{!draft.sections.some(s=>!s.hidden&&(s.kind||inferKind(s.title))==='form')&&draft.layout!=='form-side'&&<section className="composed-block"><h2>联系与咨询</h2>{content({id:'contact-form',kind:'form',title:'联系表单',body:''})}</section>}<footer id="landing-contact" className="landing-footer"><div><small>LET’S BUILD WHAT’S NEXT</small><h2>从一次交流开始。</h2></div><button className="landing-cta" onClick={()=>act(draft.goal)}>{draft.goal}<ArrowUpRight size={15}/></button></footer><div className="landing-legal">© {new Date().getFullYear()} {draft.company}<span>内容与业务信息均为示例</span></div></>}</article>
}
